#4 nginx LB 추가
JavaBlooming-In-Spring/System-Design-Interview pull request #26
Opened 2023-06-10 06:16 UTC by jojaeng2

woo-chang/#3와 연동 완료.

저는 간단하게 nginx를 뒀고 load balancing도 잘 됩니다.
다만 문제가 모니터링 도구인데, 현모가 한것 처럼 was - grafana 1대1 매핑을 하는게 맞는지 모르겠어요. 이게 맞는 것 같긴한데, 그러면 또 너무 귀찮고.. 뭐가 맞는지 몰겠네요

--scale로 스케일 아웃하면 도커가 알아서 LB를 해줘서 그냥 grafana 설정 안건드려도 알아서 2개의 컨테이너 metric 정보를 순차적으로 불러오지 않을까? 싶었는데 잘 불러오긴 하더군요.

그래서 grafana에서 보여주는 metric 정보가 2개의 컨테이너한테 순차적으로 불러오는게 맞는지 검증하고 싶었고, interceptor를 만들어서 로깅을 하려고 했는데, 실패했습니다. 
이유는 "/actuator/prometheus 엔드포인트는 스프링 부트의 메트릭 정보를 제공하기 위한 특별한 엔드포인트이기 때문이다"라고 해요. 그래서 어떻게 할까 고민하다가 AOP를 구현하려고 했는데 귀찮아서 못했습니다.

close: #4 
README 업데이트 완료

2023-06-10 09:30 UTC, hyun98 commented
프로메테우스가 스프링 컨테이너의 동적인 scale out을 감지해서 로그를 가져오려면
앞으로 서비스 디스커버리 기능이 있는 도커 스웜을 사용해야 할 것 같은데요 어떠신지들

2023-06-10 09:41 UTC, jojaeng2 commented
예 저도 필요할 것 같긴 하네요. auto scale out이 안되는 구조라..
docker swarm으로 여러 컨테이너를 하나의 서비스로 묶을 수 있는 것으로 알고 있는데, 앞으로 이런 기능이 필요하지 않을까 생각합니다

2023-06-24 05:43 UTC, gusah009 commented
https://hyeo-noo.tistory.com/217 보면서 docker-swarm이랑 docker 차이에 대해 공부중입니다 ㅎㅎ

2023-06-24 06:11 UTC, gusah009 requested changes
저 app 띄우면 요러면서 BUILD FAILED 해버립니다 ㅠㅠ 수정 부탁드려용

<img width="1230" alt="image" src="https://github.com/JavaBlooming-In-Spring/System-Design-Interview/assets/26597702/c941f5f9-7e90-43cb-a830-781ab3332642">

2023-06-24 06:41 UTC, gusah009 approved these changes
잘 동작하는거 확인했습니다~~

근데 grafana에 컨테이너 별로 안뜨는게 계속 걸리네요... 말씀하신것처럼 docker-swarm으로 바꾸면 인식 될 것 같긴 한데... 함 긔?

2023-06-24 06:45 UTC, jojaeng2 commented
ㅋㅋㅋ 고고..? 하실???

2023-06-25 12:06 UTC, merged